### ISSUE TITLE
Add to packagist

### ISSUE THREAD

**Issue by reinfi** [goaop/goaop-zend-expressive-middleware#1]
@lisachenko 

Can you add the repository to packagist. I tried to but it seems that I am not allowed to.

**Comment by lisachenko** [comment]
Done: [goaop/goaop-zend-expressive-middleware](https://packagist.org/packages/goaop/goaop-zend-expressive-middleware)

Need to configure hook for auto-update...

**Comment by lisachenko** [comment]
> Need to configure hook for auto-update...

Done
